### ISSUE TITLE
Ask for help 😊

### ISSUE THREAD

**Issue by Enantiomerie** [githubadas/docker4nightscout#1]
Hi Pablo,

my daughter got her diagnosis ON November 16th and now I want to learn how to get nightscout on my Synology NAS with docker before she will get her 640g in March. 

Would you please support me to start my journey in the T1D area with nightscout 😊? 

I saw you contributed to projects that made me assume that you created the exact setup I want to create as well. 
Everything would be of great help! 

My mail address is michael@gegner.email. 

Thank you so much in advance!

Michael

**Comment by githubadas** [comment]
You have to create two dockers:

1) mongodb docker - and create db, user and pass. For example:
https://schwabencode.com/blog/2018/07/23/Run-MongoDB-in-Docker-on-Synology

run command:
mongo -u admin

create DB:
use nightscoutdb

create user and add permisions:
db.createUser({ user: "userone1", pwd: "useronepass1", roles: [ { role: "dbOwner", db: "nightscoutdb"}]});

Link to the base to pun in mongodb in nightscout docker:
mongodb://userone1:useronepass1@<synology_IP>:37011/nightscoutdb

2) nightscout docker and put nessesary variables with dedicated mongodb link to your first container.

3) open dedicated port 1337 on your router - It's easier if you have static IP. If no you have to use any DDNS service.

Thats all.
