### ISSUE TITLE
duplicate

### ISSUE THREAD

**Issue by asquelt** [githubadas/docker4nightscout#2]
it appears that it's already covered by original maintainer.

https://github.com/nightscout/nightscout-docker
https://hub.docker.com/r/nightscout/cgm-remote-monitor

**Comment by githubadas** [comment]
The source of this project is exactly the same as in Dockerfile - as many other users who create their own container.
"Git: //github.com/nightscout/cgm-remote-monitor.git."
You can of course use the main docker - it's up to you.
